name: Deploy Github

on:
  push:
    tags: # Deploy tag (e.g. v1.0) to production
      - 'v**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Docusaurus site
        run: yarn build

      - name: Deploy to steedos.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GIT_PASS }}
          external_repository: steedos/steedos.github.io
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./build
        