name: Deploy PDF

on:
  workflow_run:
    workflows: [Deploy Site]
    types:
      - completed
  push:
    branches: 
      - 'beta'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Run Docusaurus site
        run: npm run serve

      - name: Build Developer PDF
        run: npx docs-to-pdf --initialDocURLs="http://localhost:3000/zh-CN/developer/"  --contentSelector="article"  --paginationSelector="a.pagination-nav__link.pagination-nav__link--next" --outputPDFFilename="build/steedos-developer-zh-CN.pdf" --excludeSelectors=".breadcrumbs,section.row,.theme-doc-footer" --pdfMargin="80,60,80,60" --coverTitle="Steedos Developer Documentaion"  --baseUrl="http://localhost:3000/zh-CN/developer/"  --excludePaths="/zh-CN/developer/api/openapi"

      - name: Build Platform PDF
        run: npx docs-to-pdf --initialDocURLs="http://localhost:3000/zh-CN/"  --contentSelector="article"  --paginationSelector="a.pagination-nav__link.pagination-nav__link--next" --baseUrl="http://localhost:3000/zh-CN/" --outputPDFFilename	'build/steedos-platform-zh-CN.pdf'  --excludeSelectors=".breadcrumbs,section.row,.theme-doc-footer" --pdfMargin="80,60,80,60" --coverTitle="Steedos Platform Documentaion"   --excludePaths="/zh-CN/getting-started,/zh-CN/user,/zh-CN/deploy"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: cn-northwest-1

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks 
        env:
          AWS_S3_BUCKET: docs-steedos-com
          AWS_S3_REGION: cn-northwest-1
          SOURCE_DIR: ./build/

      - name: Invalidate CloudFront distribution
        run: |
          aws cloudfront create-invalidation --distribution-id E3PZXWVY8YMW6P --paths "/*"